// Code Generated by Sidekick is for learning and experimentation purposes only.
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  base: '/',
  plugins: [react()],
  server: {
    proxy: {
        "/ado-api": {
        target: "https://dev.azure.com",
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/ado-api/, ""),
        secure: true,
        
      configure: (proxy) => {
          proxy.on('proxyReq', (proxyReq, req) => {
            console.log('[PROXY →]', req.method, req.url, '→', proxyReq.path);
          });
          proxy.on('proxyRes', (proxyRes, req) => {
            console.log('[PROXY ←]', proxyRes.statusCode, req.url,
              'content-type:', proxyRes.headers['content-type']);
          });
          proxy.on('error', (err, req) => {
            console.error('[PROXY ERR]', req.url, err.message);
          });
        },
      },
    },
  },
});