// Code Generated by Sidekick is for learning and experimentation purposes only.
import { useState, useEffect, useCallback } from "react";

// ─── ADO Config ───────────────────────────────────────────────────────────────
const ADO = {
  org:          import.meta.env.VITE_ADO_ORG,
  project:      import.meta.env.VITE_ADO_PROJECT,
  PAT:          import.meta.env.VITE_ADO_TOKEN,
  workItemType: "Issue",
  apiVersion:   "7.1",
};

// ─── Constants ────────────────────────────────────────────────────────────────
const CATEGORIES = [
  { value: "Comp Analyst Access",     icon: "🔐" },
  { value: "Consulting Services Dashboard", icon: "🗄️" },
  { value: "Audit & Assurance Dshboard", icon: "🐛" },
  { value: "DP Dashboard", icon: "⚡" },
  { value: "Tax Dashboard", icon: "🖥️" },
  { value: "Other", icon: "📋" },
];

const PRIORITIES = [
  { label: "Low",      num: 4, accent: "#22c55e", dim: "#14532d" },
  { label: "Medium",   num: 3, accent: "#f59e0b", dim: "#78350f" },
  { label: "High",     num: 2, accent: "#f97316", dim: "#7c2d12" },
  { label: "Critical", num: 1, accent: "#ef4444", dim: "#7f1d1d" },
];

const PRIORITY_EMOJI = { Low: "🟢", Medium: "🟡", High: "🟠", Critical: "🔴" };

const EMPTY_FORM = {
  name: "", email: "", title: "",
  category: "", priority: "",
  description: "", steps: "",
};

// ─── Azure DevOps API Call ────────────────────────────────────────────────────
function buildPatch(form) {
  const p = PRIORITIES.find((x) => x.label === form.priority);
  const body = `
    <b>Reporter:</b> ${form.name} &lt;${form.email}&gt;<br/>
    <b>Category:</b> ${form.category}<br/>
    <b>Priority:</b> ${form.priority}<br/><br/>
    <b>Description:</b><br/>${form.description.replace(/\n/g, "<br/>")}<br/>
    ${form.steps ? `<br/><b>Steps to Reproduce:</b><br/>${form.steps.replace(/\n/g, "<br/>")}` : ""}
  `;
  return [
    { op: "add", path: "/fields/System.Title",                        value: `[${form.category}] ${form.title}` },
    { op: "add", path: "/fields/System.Description",                  value: body },
    { op: "add", path: "/fields/Microsoft.VSTS.Common.Priority",      value: p?.num ?? 3 },
    { op: "add", path: "/fields/System.Tags",                         value: `${form.category}; ${form.priority}; Anaplan` },
  ];
}

async function postToADO(form) {
  const type = `$${ADO.workItemType}`;
  const org = encodeURIComponent(import.meta.env.VITE_ADO_ORG);
  const proj = encodeURIComponent(import.meta.env.VITE_ADO_PROJECT);
  const url  = `ado-api/${org}/${proj}/_apis/wit/workitems/${type}?api-version=${ADO.apiVersion}`;
  
  const res  = await fetch(url, {
    method:  "POST",
    headers: {
      "Content-Type":  "application/json-patch+json",
      "Authorization": `Basic ${btoa(`:${import.meta.env.VITE_ADO_TOKEN}`)}`,
    },
    body: JSON.stringify(buildPatch(form)),
  });
  
  const responseText = await res.text();

  // 🔍 Log first 500 chars so you can see what came back
  

  if (!res.ok) {
    
    let msg = `HTTP ${res.status}`;
    try { msg = JSON.parse(responseText).message || msg; } catch {}
    throw new Error(msg);
  }
   const contentType = res.headers.get('content-type') || '';
  if (!contentType.includes('application/json')) {
    throw new Error(
      `Expected JSON response but received "${contentType}". ` +
      `Check that your org name and project name are correct in your .env file.`
    );
  }

  // Parse the text we already read (can't call res.json() after res.text())
  return JSON.parse(responseText);
}
//  return res.json();


// ─── Tiny animation hook ──────────────────────────────────────────────────────
function useMounted() {
  const [mounted, setMounted] = useState(false);
  useEffect(() => { const t = setTimeout(() => setMounted(true), 30); return () => clearTimeout(t); }, []);
  return mounted;
}

// ─── Components ───────────────────────────────────────────────────────────────
function Label({ children, required }) {
  return (
    <label style={css.label}>
      {children}{required && <span style={{ color: "#f87171", marginLeft: 3 }}>*</span>}
    </label>
  );
}

function InputField({ label, name, type = "text", placeholder, value, onChange, error, icon, required }) {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 5 }}>
      <Label required={required}>{label}</Label>
      <div style={{ position: "relative" }}>
        {icon && <span style={css.fieldIcon}>{icon}</span>}
        <input
          type={type} placeholder={placeholder} value={value} autoComplete="off"
          onChange={(e) => onChange(name, e.target.value)}
          style={{ ...css.input, ...(icon ? { paddingLeft: 38 } : {}), ...(error ? css.inputErr : {}) }}
        />
      </div>
      {error && <span style={css.errTxt}>{error}</span>}
    </div>
  );
}

function TextareaField({ label, name, placeholder, value, onChange, error, rows = 4, required, hint }) {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 5 }}>
      <Label required={required}>{label}</Label>
      <textarea
        placeholder={placeholder} value={value} rows={rows}
        onChange={(e) => onChange(name, e.target.value)}
        style={{ ...css.textarea, ...(error ? css.inputErr : {}) }}
      />
      {hint  && <span style={css.hint}>{hint}</span>}
      {error && <span style={css.errTxt}>{error}</span>}
    </div>
  );
}

function CategorySelect({ value, onChange, error }) {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 5 }}>
      <Label required>Issue Category</Label>
      <div style={{ position: "relative" }}>
        <span style={css.fieldIcon}>{CATEGORIES.find((c) => c.value === value)?.icon || "📂"}</span>
        <select
          value={value} onChange={(e) => onChange("category", e.target.value)}
          style={{ ...css.select, paddingLeft: 38, ...(error ? css.inputErr : {}) }}
        >
          <option value="" disabled>Select a category…</option>
          {CATEGORIES.map((c) => (
            <option key={c.value} value={c.value}>{c.icon}  {c.value}</option>
          ))}
        </select>
      </div>
      {error && <span style={css.errTxt}>{error}</span>}
    </div>
  );
}

function PriorityPicker({ value, onChange, error }) {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
      <Label required>Priority</Label>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 8 }}>
        {PRIORITIES.map((p) => {
          const active = value === p.label;
          return (
            <button key={p.label} type="button" onClick={() => onChange("priority", p.label)}
              style={{
                ...css.priBtn,
                border: `1.5px solid ${active ? p.accent : "#374151"}`,
                background: active ? `${p.accent}18` : "#1f2937",
                color:  active ? p.accent : "#6b7280",
                fontWeight: active ? 700 : 500,
                boxShadow: active ? `0 0 14px ${p.accent}40` : "none",
                transform: active ? "scale(1.05)" : "scale(1)",
              }}
            >
              <span style={{ fontSize: 20 }}>{PRIORITY_EMOJI[p.label]}</span>
              <span style={{ fontSize: 12 }}>{p.label}</span>
            </button>
          );
        })}
      </div>
      {error && <span style={css.errTxt}>{error}</span>}
    </div>
  );
}

function ProgressBar({ step }) {
  // step: 0=reporter, 1=issue, 2=extra
  const pct = ((step + 1) / 3) * 100;
  const labels = ["Reporter", "Issue Details", "Description"];
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
      <div style={{ display: "flex", justifyContent: "space-between" }}>
        {labels.map((l, i) => (
          <span key={l} style={{ fontSize: 11, fontWeight: 600,
            color: i <= step ? "#818cf8" : "#4b5563",
            letterSpacing: "0.5px", textTransform: "uppercase" }}>
            {i <= step ? "✓ " : `${i + 1}`}.{l}
          </span>
          ))}
      </div>
      <div style={{ height: 4, background: "#1f2937", borderRadius: 99, overflow: "hidden" }}>
        <div style={{ height: "100%", width: `${pct}%`, background: "linear-gradient(90deg,#6366f1,#a78bfa)", borderRadius: 99, transition: "width 0.4s ease" }} />
      </div>
    </div>
  );
}

function SuccessScreen({ result, form, onReset }) {
  const mounted = useMounted();
  const p = PRIORITIES.find((x) => x.label === form.priority);
  const adoUrl = result?._links?.html?.href;
  const ticketId = result?.id;

  return (
    <div style={{
      ...css.successWrap,
      opacity: mounted ? 1 : 0,
      transform: mounted ? "translateY(0)" : "translateY(24px)",
      transition: "all 0.5s ease",
    }}>
      {/* Glow ring */}
      <div style={css.glowRing}>
        <div style={css.glowInner}>
          <span style={{ fontSize: 44 }}>✅</span>
        </div>
      </div>

      <h2 style={{ margin: "0 0 6px", fontSize: 26, fontWeight: 800, color: "#f9fafb", letterSpacing: "-0.5px" }}>
        Ticket Submitted!
      </h2>
      <p style={{ margin: "0 0 28px", color: "#9ca3af", fontSize: 14 }}>
        Your issue has been logged in Azure DevOps.
      </p>

      {/* Ticket ID hero */}
      <div style={css.ticketIdBox}>
        <span style={{ color: "#6b7280", fontSize: 12, fontWeight: 600, letterSpacing: "1px", textTransform: "uppercase" }}>Work Item ID</span>
        <span style={{ fontSize: 48, fontWeight: 900, color: "#818cf8", letterSpacing: "-2px", lineHeight: 1 }}>
          #{ticketId ?? "—"}
        </span>
        
      </div>

      {/* Summary grid */}
      <div style={css.summaryGrid}>
        {[
          { key: "Reporter",    val: `${form.name}` },
          { key: "Email",       val: form.email },
          { key: "Category",    val: `${CATEGORIES.find(c=>c.value===form.category)?.icon} ${form.category}` },
          { key: "Priority",    val: form.priority, color: p?.accent },
          { key: "Title",       val: form.title, span: true },
        ].map(({ key, val, color, span }) => (
          <div key={key} style={{ ...css.summaryRow, ...(span ? { gridColumn: "1 / -1" } : {}) }}>
            <span style={css.summaryKey}>{key}</span>
            <span style={{ ...css.summaryVal, ...(color ? { color, fontWeight: 700 } : {}) }}>{val}</span>
          </div>
        ))}
      </div>

      <div style={{ display: "flex", gap: 12, justifyContent: "center", flexWrap: "wrap" }}>
        <button onClick={onReset} style={css.resetBtn}>+ Submit Another Ticket</button>
        {adoUrl && (
          <a href={adoUrl} target="_blank" rel="noreferrer" style={css.outlineBtn}>
            Open in ADO ↗
          </a>
        )}
      </div>
    </div>
  );
}

function HistoryRow({ h }) {
  const p = PRIORITIES.find((x) => x.label === h.priority);
  return (
    <div style={css.hRow}>
      <span style={{ fontSize: 15 }}>{CATEGORIES.find(c=>c.value===h.category)?.icon ?? "📋"}</span>
      <span style={{ flex: 1, fontSize: 13, color: "#d1d5db", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontWeight: 500 }}>
        {h.title}
      </span>
      {p && <span style={{ fontSize: 11, fontWeight: 700, color: p.accent, background: `${p.accent}18`, padding: "2px 9px", borderRadius: 99 }}>{h.priority}</span>}
      {h.id
        ? <a href={h.url} target="_blank" rel="noreferrer" style={{ color: "#818cf8", fontSize: 12, fontWeight: 700 }}>#{h.id}</a>
        : <span style={{ color: "#f87171", fontSize: 12 }}>✗ Failed</span>}
      <span style={{ color: "#4b5563", fontSize: 11 }}>{h.time}</span>
    </div>
  );
}

// ─── Main App ─────────────────────────────────────────────────────────────────
export default function App() {
  const [form,       setForm]       = useState(EMPTY_FORM);
  const [errors,     setErrors]     = useState({});
  const [busy,       setBusy]       = useState(false);
  const [success,    setSuccess]    = useState(null); // ADO result
  const [apiErr,     setApiErr]     = useState(null);
  const [history,    setHistory]    = useState([]);
  const [showHist,   setShowHist]   = useState(false);
  const mounted = useMounted();

  const update = useCallback((key, val) => {
    setForm((f) => ({ ...f, [key]: val }));
    setErrors((e) => ({ ...e, [key]: undefined }));
  }, []);

  const validate = () => {
    const e = {};
    if (!form.name.trim())     e.name     = "Full name is required.";
    if (!form.email.trim())    e.email    = "Email address is required.";
    else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) e.email = "Enter a valid email.";
    if (!form.title.trim())    e.title    = "Issue title is required.";
    if (!form.category)        e.category = "Please select a category.";
    if (!form.priority)        e.priority = "Please select a priority level.";
    if (!form.description.trim()) e.description = "Please describe the issue.";
    return e;
  };

  // Derive progress step
  const step = (() => {
    if (form.description || form.steps) return 2;
    if (form.title || form.category || form.priority) return 1;
    return 0;
  })();

  const handleSubmit = async (e) => {
    e.preventDefault();
    const errs = validate();
    if (Object.keys(errs).length) { setErrors(errs); return; }
    setBusy(true);
   
    setApiErr(null);
    
    try {
      const result = await postToADO(form);
      
      const url = result._links?.html?.href;
      
      setHistory((h) => [{
        title: form.title, category: form.category, priority: form.priority,
        id: result.id, url, time: new Date().toLocaleTimeString(),
      }, ...h.slice(0, 9)]);
      setSuccess(result);
      
    } catch (err) {
           
      setApiErr(err.message);
        setHistory((h) => [{
        title: form.title, category: form.category, priority: form.priority,
        time: new Date().toLocaleTimeString(),
      }, ...h.slice(0, 9)]);
    } finally {
      setBusy(false);
      
    }
  };

  const handleReset = () => { setForm(EMPTY_FORM); setErrors({}); setSuccess(null); setApiErr(null); };

  // ── Render: Success ──────────────────────────────────────────────────────────
  if (success) {
    
    return (
      <div style={css.root}>
        <div style={{ ...css.shell, opacity: mounted ? 1 : 0, transition: "opacity 0.4s" }}>
          <Header />
          <SuccessScreen result={success} form={form} onReset={handleReset} />
          {history.length > 0 && (
            <div style={css.histBox}>
              <button style={css.histToggle} onClick={() => setShowHist(o => !o)}>
                {showHist ? "▾" : "▸"} Submission History ({history.length})
              </button>
              {showHist && history.map((h, i) => <HistoryRow key={i} h={h} />)}
            </div>
          )}
        </div>
      </div>
    );
  }

  // ── Render: Form ─────────────────────────────────────────────────────────────
  return (
    <div style={css.root}>
      <div style={{ ...css.shell, opacity: mounted ? 1 : 0, transform: mounted ? "translateY(0)" : "translateY(16px)", transition: "all 0.45s ease" }}>
        <Header />

        {/* Status bar */}
        <div style={css.statusBar}>
          <span style={css.statusDot} />
          <span style={{ color: "#9ca3af", fontSize: 12 }}>
            Connected to <span style={{ color: "#d1d5db", fontWeight: 600 }}>{ADO.org}</span>
            {" › "}<span style={{ color: "#d1d5db", fontWeight: 600 }}>{ADO.project}</span>
            {" · "}<span style={{ color: "#818cf8", fontWeight: 600 }}>Work Item: {ADO.workItemType}</span>
          </span>
        </div>

        {/* API error */}
        {apiErr && (
          <div style={css.apiErrBox}>
            <span style={{ fontSize: 18 }}>⚠️</span>
            <span style={{ flex: 1 }}><strong>Submission failed:</strong> {apiErr}</span>
            <button onClick={() => setApiErr(null)} style={css.closeBtn}>✕</button>
          </div>
        )}

        <form onSubmit={handleSubmit} noValidate>
          {/* Progress */}
          <div style={css.section}>
            <ProgressBar step={step} />
          </div>

          {/* Section 1 — Reporter */}
          <div style={css.section}>
            <SectionHeader icon="👤" title="Reporter Information" />
            <div style={css.grid2}>
              <InputField label="Full Name"      name="name"  placeholder="e.g. Jane Smith"         value={form.name}  onChange={update} error={errors.name}  icon="👤" required />
              <InputField label="Email Address"  name="email" placeholder="jane@company.com" type="email" value={form.email} onChange={update} error={errors.email} icon="✉️" required />
            </div>
          </div>

          {/* Divider */}
          <div style={css.divider} />

          {/* Section 2 — Issue Details */}
          <div style={css.section}>
            <SectionHeader icon="🎫" title="Issue Details" />
            <div style={{ display: "flex", flexDirection: "column", gap: 18 }}>
              <InputField
                label="Issue Title" name="title"
                placeholder="Short, clear summary of the problem"
                value={form.title} onChange={update} error={errors.title} icon="📝" required
              />
              <div style={css.grid2}>
                <CategorySelect value={form.category} onChange={update} error={errors.category} />
                <div /> {/* spacer */}
              </div>
              <PriorityPicker value={form.priority} onChange={update} error={errors.priority} />
            </div>
          </div>

          {/* Divider */}
          <div style={css.divider} />

          {/* Section 3 — Description */}
          <div style={css.section}>
            <SectionHeader icon="📄" title="Description" />
            <div style={{ display: "flex", flexDirection: "column", gap: 18 }}>
              <TextareaField
                label="Detailed Description" name="description"
                placeholder="Describe the issue — what happened, what you expected, and the impact…"
                value={form.description} onChange={update} error={errors.description} rows={5} required
              />
              <TextareaField
                label="Steps to Reproduce" name="steps"
                placeholder={"1. Navigate to…\n2. Click on…\n3. Observe that…"}
                value={form.steps} onChange={update} rows={4}
                hint="Optional — helps the team reproduce the issue faster."
              />
            </div>
          </div>

          {/* Submit */}
          <div style={{ padding: "0 28px 28px" }}>
            <button type="submit" disabled={busy} style={{ ...css.submitBtn, ...(busy ? css.submitBusy : {}) }}>
              {busy ? (
                <span style={{ display: "flex", alignItems: "center", gap: 10, justifyContent: "center" }}>
                  <span style={css.spinner} />
                  Submitting to Azure DevOps…
                </span>
              ) : "🚀  Submit Support Ticket"}
            </button>
          </div>
        </form>

        {/* History */}
        {history.length > 0 && (
          <div style={css.histBox}>
            <button style={css.histToggle} onClick={() => setShowHist(o => !o)}>
              {showHist ? "▾" : "▸"} Submission History ({history.length})
            </button>
            {showHist && history.map((h, i) => <HistoryRow key={i} h={h} />)}
          </div>
        )}
        {history.length > 0 && (
        <p style={css.footer}>
          Your ticket has been submitted.
        </p>
        )}
      </div>

      {/* Keyframe injection */}
      <style>{`
        @keyframes spin { to { transform: rotate(360deg); } }
        @keyframes pulse-ring { 0%,100% { box-shadow: 0 0 0 0 #6366f140; } 50% { box-shadow: 0 0 0 14px #6366f100; } }
        select option { background: #1f2937; color: #f9fafb; }
        input::placeholder, textarea::placeholder { color: #4b5563; }
        input:focus, textarea:focus, select:focus { border-color: #6366f1 !important; outline: none; box-shadow: 0 0 0 3px #6366f133; }
        button:hover:not(:disabled) { filter: brightness(1.08); }
        ::-webkit-scrollbar { width: 6px; } ::-webkit-scrollbar-track { background: #111827; } ::-webkit-scrollbar-thumb { background: #374151; border-radius: 99px; }
      `}</style>
    </div>
  );
}

function Header() {
  return (
    <div style={css.header}>
      <div style={css.headerGlow} />
      <div style={{ position: "relative", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 16, flexWrap: "wrap" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
          <div style={css.logoBox}>
            <span style={{ fontSize: 30 }}>🎫</span>
          </div>
          <div>
            <h1 style={css.headerTitle}>Anaplan Support Portal</h1>
            <p style={css.headerSub}>Report issues · Track submissions · Powered by Azure DevOps</p>
          </div>
        </div>
        <div style={css.headerTag}>
          <span style={{ color: "#818cf8", fontWeight: 800 }}>TechCoE</span>
          <span style={{ color: "#4b5563" }}>Testing</span>
        </div>
      </div>
    </div>
  );
}

function SectionHeader({ icon, title }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 16 }}>
      <span style={{ fontSize: 18 }}>{icon}</span>
      <span style={{ fontSize: 14, fontWeight: 700, color: "#e5e7eb", letterSpacing: "0.3px" }}>{title}</span>
      <div style={{ flex: 1, height: 1, background: "#1f2937", marginLeft: 8 }} />
    </div>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────
const css = {
  root: {
    minHeight: "100vh",
    background: "#030712",
    backgroundImage: "radial-gradient(ellipse at 20% 20%, #1e1b4b44 0%, transparent 60%), radial-gradient(ellipse at 80% 80%, #1c0d3344 0%, transparent 60%)",
    padding: "28px 16px 56px",
    fontFamily: "'Inter', system-ui, sans-serif",
    color: "#f9fafb",
  },
  shell: {
    maxWidth: 720,
    margin: "0 auto",
    background: "#0f172a",
    borderRadius: 20,
    border: "1px solid #1e293b",
    boxShadow: "0 24px 80px rgba(0,0,0,0.7), 0 0 0 1px #1e293b",
    overflow: "hidden",
  },
  header: {
    position: "relative",
    background: "linear-gradient(135deg, #0f0c29 0%, #1e1b4b 50%, #1a0533 100%)",
    padding: "28px 28px 24px",
    borderBottom: "1px solid #1e293b",
    overflow: "hidden",
  },
  headerGlow: {
    position: "absolute", top: -60, left: "50%", transform: "translateX(-50%)",
    width: 400, height: 200,
    background: "radial-gradient(ellipse, #6366f133 0%, transparent 70%)",
    pointerEvents: "none",
  },
  logoBox: {
    width: 58, height: 58,
    background: "linear-gradient(135deg, #312e81, #6d28d9)",
    borderRadius: 14,
    display: "flex", alignItems: "center", justifyContent: "center",
    boxShadow: "0 4px 20px #6366f155",
  },
  headerTitle: { margin: 0, fontSize: 22, fontWeight: 800, color: "#f9fafb", letterSpacing: "-0.4px" },
  headerSub:   { margin: "4px 0 0", color: "#6b7280", fontSize: 12 },
  headerTag: {
    background: "#0f172a",
    border: "1px solid #1e293b",
    borderRadius: 99,
    padding: "6px 16px",
    fontSize: 13,
    letterSpacing: "0.3px",
  },
  statusBar: {
    display: "flex", alignItems: "center", gap: 8,
    padding: "10px 28px",
    background: "#0a0f1e",
    borderBottom: "1px solid #1e293b",
  },
  statusDot: {
    width: 8, height: 8, borderRadius: "50%",
    background: "#22c55e",
    boxShadow: "0 0 6px #22c55e",
    flexShrink: 0,
    animation: "pulse-ring 2s infinite",
  },
  apiErrBox: {
    display: "flex", alignItems: "center", gap: 10,
    margin: "16px 28px 0",
    background: "#1c0707",
    border: "1px solid #7f1d1d",
    borderRadius: 10,
    padding: "12px 16px",
    color: "#fca5a5",
    fontSize: 13,
  },
  closeBtn: { background: "none", border: "none", color: "#f87171", cursor: "pointer", fontSize: 16, padding: 0 },
  section:  { padding: "24px 28px 0" },
  divider:  { height: 1, background: "#1e293b", margin: "24px 28px 0" },
  grid2:    { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "14px 20px" },
  label:    { fontSize: 12, fontWeight: 600, color: "#9ca3af", letterSpacing: "0.5px", textTransform: "uppercase" },
  input: {
    width: "100%", boxSizing: "border-box",
    padding: "10px 13px",
    background: "#1f2937",
    border: "1.5px solid #374151",
    borderRadius: 9,
    color: "#f3f4f6",
    fontSize: 14,
    transition: "border-color 0.15s, box-shadow 0.15s",
  },
  select: {
    width: "100%", boxSizing: "border-box",
    padding: "10px 13px",
    background: "#1f2937",
    border: "1.5px solid #374151",
    borderRadius: 9,
    color: "#f3f4f6",
    fontSize: 14,
    cursor: "pointer",
    appearance: "none",
  },
  textarea: {
    width: "100%", boxSizing: "border-box",
    padding: "10px 13px",
    background: "#1f2937",
    border: "1.5px solid #374151",
    borderRadius: 9,
    color: "#f3f4f6",
    fontSize: 14,
    resize: "vertical",
    fontFamily: "inherit",
    lineHeight: 1.6,
    transition: "border-color 0.15s, box-shadow 0.15s",
  },
  inputErr: { borderColor: "#dc2626", background: "#1c0707" },
  errTxt:   { fontSize: 11, color: "#f87171", marginTop: 1 },
  hint:     { fontSize: 11, color: "#4b5563", marginTop: 2 },
  fieldIcon: {
    position: "absolute", left: 11, top: "50%", transform: "translateY(-50%)",
    fontSize: 15, pointerEvents: "none", userSelect: "none",
  },
  priBtn: {
    display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
    gap: 5, padding: "12px 6px",
    borderRadius: 10, cursor: "pointer",
    transition: "all 0.17s ease",
    outline: "none", fontFamily: "inherit",
  },
  submitBtn: {
    width: "100%",
    padding: "15px",
    background: "linear-gradient(135deg, #4338ca, #7c3aed, #6d28d9)",
    backgroundSize: "200% 200%",
    color: "#fff",
    border: "none",
    borderRadius: 12,
    fontSize: 16,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 4px 24px #6366f155",
    letterSpacing: "0.2px",
    transition: "opacity 0.2s, transform 0.15s",
  },
  submitBusy: { opacity: 0.6, cursor: "not-allowed" },
  spinner: {
    display: "inline-block",
    width: 18, height: 18,
    border: "2.5px solid rgba(255,255,255,0.25)",
    borderTop: "2.5px solid #fff",
    borderRadius: "50%",
    animation: "spin 0.7s linear infinite",
  },
  // Success
  successWrap: {
    padding: "44px 32px 36px",
    display: "flex", flexDirection: "column", alignItems: "center",
    gap: 0, textAlign: "center",
  },
  glowRing: {
    width: 96, height: 96,
    borderRadius: "50%",
    background: "radial-gradient(circle, #22c55e22, transparent 70%)",
    display: "flex", alignItems: "center", justifyContent: "center",
    marginBottom: 20,
    boxShadow: "0 0 40px #22c55e33",
    animation: "pulse-ring 2.5s infinite",
  },
  glowInner: {
    width: 72, height: 72, borderRadius: "50%",
    background: "#052e16",
    border: "2px solid #16a34a",
    display: "flex", alignItems: "center", justifyContent: "center",
  },
  ticketIdBox: {
    display: "flex", flexDirection: "column", alignItems: "center", gap: 6,
    background: "#0f172a",
    border: "1px solid #1e293b",
    borderRadius: 16,
    padding: "24px 48px",
    margin: "16px 0 20px",
    width: "100%", maxWidth: 360, boxSizing: "border-box",
  },
  adoLink: {
    color: "#818cf8", fontSize: 13, fontWeight: 600,
    textDecoration: "none", marginTop: 4,
  },
  summaryGrid: {
    display: "grid", gridTemplateColumns: "1fr 1fr",
    gap: 1,
    background: "#1e293b",
    border: "1px solid #1e293b",
    borderRadius: 12,
    overflow: "hidden",
    width: "100%", maxWidth: 480,
    marginBottom: 24,
  },
  summaryRow: {
    display: "flex", flexDirection: "column", gap: 3,
    padding: "12px 16px",
    background: "#0f172a",
  },
  summaryKey: { fontSize: 10, color: "#4b5563", fontWeight: 700, letterSpacing: "0.8px", textTransform: "uppercase" },
  summaryVal: { fontSize: 13, color: "#e5e7eb", fontWeight: 500 },
  resetBtn: {
    padding: "11px 26px",
    background: "linear-gradient(135deg, #4338ca, #7c3aed)",
    color: "#fff", border: "none", borderRadius: 10,
    fontSize: 14, fontWeight: 700, cursor: "pointer",
    boxShadow: "0 4px 16px #6366f144",
  },
  outlineBtn: {
    padding: "11px 26px",
    background: "transparent",
    color: "#818cf8",
    border: "1.5px solid #4338ca",
    borderRadius: 10,
    fontSize: 14, fontWeight: 700, textDecoration: "none",
    display: "inline-flex", alignItems: "center",
  },
  // History
  histBox: {
    margin: "16px 28px",
    background: "#0a0f1e",
    border: "1px solid #1e293b",
    borderRadius: 12,
    padding: "14px 16px",
    display: "flex", flexDirection: "column", gap: 8,
  },
  histToggle: {
    background: "none", border: "none",
    color: "#818cf8", fontSize: 13, fontWeight: 700, cursor: "pointer",
    padding: 0, textAlign: "left",
  },
  hRow: {
    display: "flex", alignItems: "center", gap: 10,
    padding: "8px 10px",
    background: "#0f172a",
    borderRadius: 8,
  },
  footer: { textAlign: "center", color: "#374151", fontSize: 11, padding: "16px 28px 28px", margin: 0 },
};
